### ISSUE TITLE
MAP parameter set not being correctly returned in MCMC python wrapper scripts

### ISSUE THREAD

**Issue by LeahJB** [NIVANorge/Mobius#8]
In the run_mcmc function in the python wrapper, it looks like results.params actually returns the median of the posterior, without taking burnin into account, rather than the MAP. Need to calculate the MAP manually (discarding burn-in) instead. As it is easy to do, can we also return the median of the posterior, as this is useful too. Ideally discarding burn-in before calculating it.

**Comment by JamesSample** [comment]
Fixed by c3afaf1f9c766bb6e0ecfb0563563c35d76ca508.

For MCMC runs, `result.params` was returning the **median** of the marginal posteriors *before* any burning and thinning, which obviously gives poor results.

Now adjusted so that `result.params` gives the **median** *after* burn-in and thinning. Both median and MAP parameter sets are also now stored in the `user_data` attribute of the `result` object and can be accessed as follows:

    result.params[par].user_data['median']
    result.params[par].user_data['map']

I have also modified the functions `set_parameter_values()` and `gof_stats()` in `mobius_calib_uncert_lmfit.py` to accept an additional kwarg `use_stat`, which defaults to `None` but can be alternatively set to either `'median'` or `'map'`. This only applies when the `result` object being passed to these functions is the output from an MCMC run (not an optimiser). Use it to specify whether you want to use the median or MAP parameter set from the MCMC. 

See the updated [example notebook](https://nbviewer.jupyter.org/github/NIVANorge/Mobius/blob/master/PythonWrapper/SimplyP/simplyp_calibration.ipynb) for more details.
